### ISSUE TITLE
Current Flathub version of NoMachine is broken

### ISSUE THREAD

**Issue by Sickday** [flathub/com.nomachine.nxplayer#9]
Greetings,

Attempting to install the NoMachine client from flathub currently results in the below error:
```
Error: While trying to apply extra data: apply_extra script failed, exit status 32512
error: Failed to install com.nomachine.nxplayer: While trying to apply extra data: apply_extra script failed, exit status 32512
```

A previous [PR](https://github.com/flathub/com.nomachine.nxplayer/pull/7) existed which addressed this issue but was never merged and was closed 3 weeks ago at the time of writing. I have also made a [PR](https://github.com/flathub/com.nomachine.nxplayer/pull/8) to update the manifest to ensure the latest version is used, but it hasn't been merged either. 

I personally use this package every day for work and it's crucial my client stay update to date thanks to compliance software in my workplace. I can't directly speak for others, but it appears this package is still being installed on a regular basis by other flathub users. Having it unavailable for install makes it difficult for those who are not using the distributions that NoMachine ships packages for. Please consider reviewing my [PR](https://github.com/flathub/com.nomachine.nxplayer/pull/8) and providing feedback if any changes are necessary. Thanks

**Comment by ConsularParadi** [comment]
Hi @Sickday, it looks like you have forked and applied the necessary updates to the repo. Could you please instruct me on how to install the nomachine app using your github repository?

**Comment by Sickday** [comment]
> Hi @Sickday, it looks like you have forked and applied the necessary updates to the repo. Could you please instruct me on how to install the nomachine app using your github repository?

Sure. A build is available via the automated build bot and can be installed with the following command.

```
flatpak install --user https://dl.flathub.org/build-repo/123282/com.nomachine.nxplayer.flatpakref
```

Alternatively, you can clone my branch, then build and install directly from the top-level directory with `flatpak-builder`.

```shell
$ git clone https://github.com/Sickday/com.nomachine.nxplayer.git
$ cd com.nomachine.nxplayer
$ flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install builddir com.nomachine.nxplayer.yml
```

**Comment by gregallem** [comment]
Hi,
I tried to install but flatpak install --user https://dl.flathub.org/build-repo/123282/com.nomachine.nxplayer.flatpakref. returned:Can't load uri https://dl.flathub.org/build-repo/123282/com.nomachine.nxplayer.flatpakref: Server returned status 404
Thanks any help will be appreciated.

**Comment by gregallem** [comment]
Hi
I tried to install with
`flatpak install --user https://dl.flathub.org/build-repo/123282/com.nomachine.nxplayer.flatpakref`
But returned
`error: Can't load uri https://dl.flathub.org/build-repo/123282/com.nomachine.nxplayer.flatpakref: Server returned status 404`
Any assistance appreciated.

**Comment by ConsularParadi** [comment]
> Sure. A build is available via the automated build bot and can be installed with the following command.
> 
> ```shell
> flatpak install --user https://dl.flathub.org/build-repo/123282/com.nomachine.nxplayer.flatpakref
> ```
@gregallem This command gives the same error as you mentioned.
> 
> Alternatively, you can clone my branch, then build and install directly from the top-level directory with `flatpak-builder`.
> 
> ```shell
> $ git clone https://github.com/Sickday/com.nomachine.nxplayer.git
> $ cd com.nomachine.nxplayer
> $ flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install builddir com.nomachine.nxplayer.yml
> ```
Instead try out this method. I can confirm that it works. I was having issues with the `--install-deps-from=flathub` flag so I removed it. You may have to install the dependencies on your own. In my case, it wasn't necessary. 

@Sickday Thank you for helping out.

**Comment by JLT032** [comment]
still broken, quite sad for a software company
the .rpm is also broken after install
 trying out a novel way of marketing ?


flatpak  install com.nomachine.nxplayer
Looking for matches…

com.nomachine.nxplayer permissions:
    ipc           network      pulseaudio      x11     dri     file access [1]
    tags [2]

    [1] xdg-documents, xdg-download
    [2] proprietary


        ID                              Branch          Op          Remote          Download
 1. [✗] com.nomachine.nxplayer          stable          i           flathub         27.4 kB / 255.8 kB

Error: Wrong size for extra data https://download.nomachine.com/download/8.11/Linux/nomachine-enterprise-client_8.11.3_4_x86_64.tar.gz
error: Failed to install com.nomachine.nxplayer: Wrong size for extra data https://download.nomachine.com/download/8.11/Linux/nomachine-enterprise-client_8.11.3_4_x86_64.tar.gz

**Comment by Sickday** [comment]
> still broken, quite sad for a software company the .rpm is also broken after install trying out a novel way of marketing ?
> 
> flatpak install com.nomachine.nxplayer Looking for matches…
> 
> com.nomachine.nxplayer permissions: ipc network pulseaudio x11 dri file access [1] tags [2]
> 
> ```
> [1] xdg-documents, xdg-download
> [2] proprietary
> 
> 
>     ID                              Branch          Op          Remote          Download
> ```
> 
>     1. [✗] com.nomachine.nxplayer          stable          i           flathub         27.4 kB / 255.8 kB
> 
> 
> Error: Wrong size for extra data https://download.nomachine.com/download/8.11/Linux/nomachine-enterprise-client_8.11.3_4_x86_64.tar.gz error: Failed to install com.nomachine.nxplayer: Wrong size for extra data https://download.nomachine.com/download/8.11/Linux/nomachine-enterprise-client_8.11.3_4_x86_64.tar.gz


Hi. To my knowledge, NoMachine as a company has no involvement in this flatpak's maintenance. The error you're seeing is due to the version on flathub being out of date.

I've had a PR open for a few months now that I continue to keep up to date with the latest version of NoMachine Enterprise Client (currently 8.14). You can use my fork with the following commands. 

```shell
$ git clone https://github.com/Sickday/com.nomachine.nxplayer.git
$ cd com.nomachine.nxplayer
$ flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install builddir com.nomachine.nxplayer.yml
```

**Comment by gregallem** [comment]
Thanks for all your work. It is working well
